src/Shop/StoreBundle/Entity/Property.php
<?php

namespace Shop\StoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Shop\StoreBundle\Entity\PropertyValues;
use Shop\StoreBundle\Repository\PropertyRepository;

/**
 * Property
 *
 * @ORM\Table(name="Property")
 * @ORM\Entity(repositoryClass="Shop\StoreBundle\Repository\PropertyRepository")
 */
class Property
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var integer
     *
     * @ORM\Column(name="type_value", type="smallint")
     */
    private $type_value;

    /**
     * @ORM\OneToMany(targetEntity="Shop\StoreBundle\Entity\PropertyValues", mappedBy="Property")
     */
    protected $Property_values;

    public function __construct()
    {
        $this->Property_values = new ArrayCollection();
    }
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Property
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set type_value
     *
     * @param integer $typeValue
     * @return Property
     */
    public function setTypeValue($typeValue)
    {
        $this->type_value = $typeValue;
    
        return $this;
    }

    /**
     * Get type_value
     *
     * @return integer 
     */
    public function getTypeValue()
    {
        return $this->type_value;
    }

    /**
     * Add Property_values
     *
     * @param PropertyValues $PropertyValues
     * @return Property
     */
    public function addPropertyValue(PropertyValues $PropertyValues)
    {
        $this->Property_values[] = $PropertyValues;
    
        return $this;
    }

    /**
     * Remove Property_values
     *
     * @param PropertyValues $PropertyValues
     */
    public function removePropertyValue(PropertyValues $PropertyValues)
    {
        $this->Property_values->removeElement($PropertyValues);
    }

    /**
     * Get Property_values
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPropertyValues()
    {
        return $this->Property_values;
    }
}

src/Shop/StoreBundle/Entity/PropertyValues.php
<?php

namespace Shop\StoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Shop\StoreBundle\Entity\Property;
use Shop\StoreBundle\Repository\PropertyValuesRepository;

/**
 * @ORM\Entity(repositoryClass="Shop\StoreBundle\Repository\PropertyValuesRepository")
 * @ORM\Table(name="Property_values")
 */
class PropertyValues
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="property_id", type="integer")
     */
    private $property_id;

    /**
     * @var string
     *
     * @ORM\Column(name="value", type="string", length=128)
     */
    private $value;

    /**
     * @var integer
     *
     * @ORM\Column(name="position", type="integer")
     */
    private $position;

    /**
     * @ORM\ManyToOne(targetEntity="Shop\StoreBundle\Entity\Property", inversedBy="Property_values")
     * @ORM\JoinColumn(name="property_id", referencedColumnName="id")
     */
    protected $Property;
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set value
     *
     * @param string $value
     * @return PropertyValues
     */
    public function setValue($value)
    {
        $this->value = $value;
    
        return $this;
    }

    /**
     * Get value
     *
     * @return string 
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Set property_id
     *
     * @param integer $PropertyId
     * @return PropertyValues
     */
    public function setPropertyId($PropertyId)
    {
        $this->property_id = $PropertyId;
    
        return $this;
    }

    /**
     * Get property_id
     *
     * @return integer 
     */
    public function getPropertyId()
    {
        return $this->property_id;
    }

 

    /**
     * Set Property
     *
     * @param Property $Property
     * @return PropertyValues
     */
    public function setProperty(Property $Property = null)
    {
        $this->Property = $Property;
    
        return $this;
    }

    /**
     * Get Property
     *
     * @return Property
     */
    public function getProperty()
    {
        return $this->Property;
    }

    /**
     * Set position
     *
     * @param integer $position
     * @return PropertyValues
     */
    public function setPosition($position)
    {
        $this->position = $position;
    
        return $this;
    }

    /**
     * Get position
     *
     * @return integer 
     */
    public function getPosition()
    {
        return $this->position;
    }
}

src/Shop/StoreBundle/Controller/PropertyController.php
<?php

namespace Shop\StoreBundle\Controller;

use Shop\StoreBundle\Form\Type\PropertyEditFormType;
use Shop\StoreBundle\Form\Type\PropertyValuesEditFormType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use Shop\StoreBundle\Entity\Property;
use Shop\StoreBundle\Repository\PropertyValuesRepository;
use Shop\StoreBundle\Entity\PropertyValues;
use Shop\StoreBundle\Form\Type\PropertyCreateFormType ;
use Shop\StoreBundle\Form\Type\PropertyValuesCreateFormType ;
use Shop\StoreBundle\Form\Type\PropertyFormType ;

class PropertyController extends Controller
{
    public function __construct()
    {
    }

    public function indexAction($page=1)
    {
        $em = $this->getDoctrine()->getManager();
        $all_count = $em->getRepository('ShopStoreBundle:Property')->findCountProperty();
        if( $all_count>0)
        {
         ld(' all='.$all_count.'  page='.$page);
            $service_route = $this->container->get('router');
            $pagen_service = $this->get('shop_store.Pagen');
            $pagen_service->setInterval_page(2);
            $pagen_service->setItems_per_page(2);
            $route = 'shop_store_property';
            $route_parameters = array( 'page'=>$page );
            $pager = $pagen_service->myPaginat( $all_count, $route,$route_parameters,$page,$service_route);
            $page = $pagen_service->getPage();
            $limit = $pagen_service->getItems_per_page();
            $offset = ($page-1)*$limit;
            ld(' limit='.$limit.'  off='.$offset);
            $Property = $em->getRepository('ShopStoreBundle:Property')->
                findAllPropertyDBAL($offset,$limit);
            ld($Property);
        }
        else{
            $param_url = array();
            $pager = '';
        }
        return $this->render('ShopStoreBundle:Property:index.html.twig',
            ['propertys'=>$Property, 'pager' => $pager, ]
        );
    }

    public function createAction(Request $request)
    {
        $Property = new Property;
        $class='Shop\StoreBundle\Entity\Property';
        $form = $this->createForm(new PropertyCreateFormType($class),  $Property);
        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($Property);
                $em->flush($Property);
                return $this->redirect($this->generateUrl('shop_store_property',['page'=>1 ]));
            }
        }
        return $this->render('ShopStoreBundle:Property:createProperty.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param Request $request
     * @param int $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function editAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $Property = $em->getRepository('ShopStoreBundle:Property')->find($id);

        $class='Shop\StoreBundle\Entity\Property';

        $form = $this->createForm(new PropertyEditFormType($class), $Property);
        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $em->flush($Property);

                return $this->redirect($this->generateUrl('shop_store_property', ['page'=>1 ]));
            }
        }

        return $this->render('ShopStoreBundle:Property:editProperty.html.twig', [
            'form' => $form->createView(),'id'=>$id,
        ]);
    }

    public function indexPropertyValuesAction($id_property,$page=1)
    {
        $em = $this->getDoctrine()->getManager();
        $all_count = $em->getRepository('ShopStoreBundle:PropertyValues')->
            findCountPropertyValues($id_property);

        if( $all_count>0)
        {
            $service_route = $this->container->get('router');
            $pagen_service = $this->get('shop_store.Pagen');
            $pagen_service->setInterval_page(2);
            $pagen_service->setItems_per_page(4);
            $route = 'shop_store_propertyValues';
            $route_parameters = array( 'id_property'=>$id_property, 'page'=>$page );
            $pager = $pagen_service->myPaginat( $all_count, $route,$route_parameters,$page,$service_route);
            $page = $pagen_service->getPage();
            $limit = $pagen_service->getItems_per_page();
            $offset = ($page-1)*$limit;
            $Property_values = $em->getRepository('ShopStoreBundle:PropertyValues')->
                findAllPropertyValuesDBAL($id_property,$offset,$limit);
            $propertyValuesService = $this->get('shop_store.PropertyValues');
            $param_url = $propertyValuesService->getUrlDbal( $Property_values );
        }
        else{
            $param_url = array();
            $Property_values = array();
            $pager = '';
        }
        return $this->render('ShopStoreBundle:Property:indexPropertyValues.html.twig',
            [
                'property_values' => $Property_values,
                'id_property' => $id_property,
                'param_url' => $param_url,
                'pager' => $pager,
                'page' => $page,
            ]);
    }

    public function createPropertyValuesAction(Request $request,$id_property)
    {
        $table_Property = new PropertyValues;
        $class='Shop\StoreBundle\Entity\PropertyValues';
        $form = $this->createForm(new PropertyValuesCreateFormType($class), $table_Property);
        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $count_Property_values = (int) $em->getRepository('ShopStoreBundle:PropertyValues')->
                    findCountPropertyValues($id_property);
            //    $table_Property->setPropertyId((int) $id_Property);
                $table_Property->setPosition($count_Property_values+1);
                $Property=$em->getRepository('ShopStoreBundle:Property')->find($id_property);
                $table_Property->setProperty($Property);
                $em->persist($table_Property);
                $em->flush($table_Property);
                return $this->redirect($this->generateUrl('shop_store_propertyValues',
                    ['id_property'=>$id_property, 'page'=>1 ]));
            }
        }
        return $this->render('ShopStoreBundle:Property:createPropertyValues.html.twig', [
            'form' => $form->createView(),'id_property'=>$id_property,
        ]);
    }

    public function editPropertyValuesAction(Request $request,$id_value_Property,$page)
    {
        $em = $this->getDoctrine()->getManager();
        $Property_value =$em->getRepository('ShopStoreBundle:PropertyValues')->
            find($id_value_Property);
        $class='Shop\StoreBundle\Entity\PropertyValues';
        $form = $this->createForm(new PropertyValuesEditFormType($class), $Property_value);
        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $em->flush($Property_value);
                return $this->redirect($this->generateUrl('shop_store_propertyValues',
                    ['id_property'=>$Property_value->getPropertyId(),'page'=>$page]));
            }
        }

        return $this->render('ShopStoreBundle:Property:editPropertyValues.html.twig', [
            'form' => $form->createView(),'id'=>$id_value_Property,'page'=>$page
        ]);
    }

    public function upPropertyValuesAction(Request $request,$id,$page)
    {
        $em = $this->getDoctrine()->getManager();
        $Property_value = $em->getRepository('ShopStoreBundle:PropertyValues')->find($id);
        $position = $Property_value->getPosition();
        $property_id = $Property_value->getPropertyId();
 //       ld($Property_value);
        $Property_value_up = $em->getRepository('ShopStoreBundle:PropertyValues')->
            findUpPropertyValues($id,$property_id,$position);
        if( is_object($Property_value_up) )
        {
            $Property_value->setPosition($position-1);
            $Property_value_up->setPosition($position);
            $em->persist($Property_value_up);
            $em->flush($Property_value_up);
        }
        else{
            $Property_value->setPosition(1);
        }
        $em->persist($Property_value);
        $em->flush($Property_value);
           //ld($Property_value);           ld('aaaa');         ld($Property_value_up);        exit;
        return $this->redirect($this->generateUrl('shop_store_propertyValues',
            ['id_property'=>$Property_value->getPropertyId(),'page'=>$page]));
    }

    public function downPropertyValuesAction(Request $request,$id,$page)
    {
        $em = $this->getDoctrine()->getManager();
        $Property_value = $em->getRepository('ShopStoreBundle:PropertyValues')->find($id);
        $position = $Property_value->getPosition();
        $property_id = $Property_value->getPropertyId();
        $Property_value_down = $em->getRepository('ShopStoreBundle:PropertyValues')->
            findDownPropertyValues($id,$property_id,$position);
        if( is_object($Property_value_down) )
        {
            $Property_value->setPosition($position+1);
            $Property_value_down->setPosition($position);
            $em->flush($Property_value_down);
            $em->flush($Property_value);
        }
        return $this->redirect($this->generateUrl('shop_store_propertyValues',
            ['id_property'=>$Property_value->getPropertyId(),'page'=>$page]));
    }
}

src/Shop/StoreBundle/Resources/views/Property/createProperty.html.twig
{% extends 'ShopStoreBundle::layout.html.twig' %}

{% block admin_content %}
    <form action="{{ path('shop_store_property_create') }}" method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}
    </form>
{% endblock admin_content %}

src/Shop/StoreBundle/Resources/views/Property/createPropertyValues.html.twig
{% extends 'ShopStoreBundle::layout.html.twig' %}

{% block admin_content %}
    <form action="{{ path('shop_store_propertyValues_create',{'id_property': id_property}) }}" method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}

    </form>
{% endblock admin_content %}

src/Shop/StoreBundle/Resources/views/Property/editProperty.html.twig
{% extends 'ShopStoreBundle::layout.html.twig' %}

{% block admin_content %}
    <form action="{{ path('shop_store_property_edit',{'id': id}) }}" method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}

    </form>
{% endblock admin_content %}

src/Shop/StoreBundle/Resources/views/Property/editPropertyValues.html.twig
{% extends 'ShopStoreBundle::layout.html.twig' %}

{% block admin_content %}
    <form action="{{ path('shop_store_propertyValues_edit',{'id_value_property': id,'page': page}) }}" method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}

    </form>
{% endblock admin_content %}

src/Shop/StoreBundle/Resources/views/Property/index.html.twig
{% extends 'ShopStoreBundle::layout.html.twig' %}

{% block admin_content %}
    <a href="{{ path('shop_store_property_create') }}">
        Добавить свойство
    </a>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Название</th>
            <th>Редактировать</th>
            <th>Значения свойства</th>
        </tr>
        </thead>
        <tbody>
        {% set max_i = propertys|length %}
        {% if max_i>0 %}
        {% endif %}
        </tbody>
        {% for i in 0..max_i-1 %}
            <tr>
                <td>{{ propertys[i].id }}</td>
                <td>{{ propertys[i].name }}</td>
                <td>
                    <a href="{{ path('shop_store_property_edit', {'id': propertys[i].id}) }}">
                        edit
                    </a>
                </td>
                <td>
                    <a href="{{ path('shop_store_propertyValues', {'id_property': propertys[i].id,'page' : 1 } ) }}">
                        value
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>
    {{ pager|raw }}
{% endblock admin_content %}

src/Shop/StoreBundle/Resources/views/Property/indexPropertyValues.html.twig
{% extends 'ShopStoreBundle::layout.html.twig' %}

{% block admin_content %}
    <a href="{{ path('shop_store_propertyValues_create', {'id_property': id_property} ) }}">
        Добавить значение свойства
    </a>
    &nbsp;
    <a href="{{ path('shop_store_property',{'page': 1}) }}">
        Таблица свойств
    </a>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Название Атрибута</th>
            <th>Значение</th>
            <th>Номер</th>
            <th>Редактировать</th>
            <th>Вверх</th>
            <th>Вниз</th>
        </tr>
        </thead>
        <tbody>
      {#  {% for value in property_values %} #}
      {#        <td>{{ property_values[i].property.name }}</td>  #}
        {% set max_i = property_values|length %}
        {% if max_i>0 %}
            {% for i in 0..max_i-1 %}
                <tr>
                   <td>{{ property_values[i].id }}</td>
                   <td>{{ property_values[i].name }}</td>
                   <td>{{ property_values[i].value }}</td>
                   <td>{{ property_values[i].position }}</td>
                   <td>
                        <a href="{{ path('shop_store_propertyValues_edit', {'id_value_property': property_values[i].id,'page': page} ) }}">
                            edit
                        </a>
                   </td>
                    <td>
                        <a href="{{ path('shop_store_propertyValues_up',{'id': param_url[i][0],'page': page}) }}">
                            up
                        </a>
                    </td>
                    <td>
                        <a href="{{ path('shop_store_propertyValues_down',{'id': param_url[i][0],'page': page}) }}">
                            down
                        </a>
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
    {{ pager|raw }}
{% endblock admin_content %}